[user]
name = "Morten Siebuhr"
email = "morten.siebuhr@group.one"

[aliases]
head = ['log', '--revisions', 'latest(all(), 20)']
rebase-all = ['rebase', '--branch', 'all:mutable() & mine()', '--destination', 'main@origin']

[git]
# Get remote branches when doing `jj git fetch` <https://martinvonz.github.io/jj/latest/github/#working-with-other-peoples-branches>
#auto-local-bookmark = true
push-bookmark-prefix = "msi/push-"

[signing]
sign-all = true
backend = "ssh"
key = "/home/msi/.ssh/id_rsa_gitlab"

[fix.tools.buildifer]
command = ["buildifier", "-lint=fix", "-path=$path"]
patterns = ["glob:**/*.bazel", "glob:**/*.bzl", "WORKSPACE"]

[ui]
diff-editor = ":builtin"
default-command = "log"
