[user]
name = "Morten Siebuhr"
email = "morten.siebuhr@group.one"

# See https://jj-vcs.github.io/jj/latest/config/#author-format
[template-aliases]
# I'm usually always working with group.one-users, so let's drop the domain-part
'format_short_signature(signature)' = 'signature.email().local()'

[aliases]
head = ['log', '--revisions', 'latest(all(), 20)']
rebase-all = ['rebase', '--branch', 'all:mutable() & mine()', '--destination', 'trunk()']

[git]
push-bookmark-prefix = "msi/push-"

[signing]
sign-all = true
backend = "ssh"
key = "/home/msi/.ssh/id_rsa_gitlab"

[fix.tools.buildifer]
command = ["buildifier", "-lint=fix", "-path=$path"]
patterns = ["glob:**/*.bazel", "glob:**/*.bzl", "WORKSPACE"]

[fix.tools.justfile-format]
command = ["just", "--justfile", "/dev/stdin", "--dump"]
patterns = ["justfile", ".justfile"]

[ui]
diff-editor = ":builtin"
default-command = "log"
