[user]
name = "Morten Siebuhr"
email = "morten.siebuhr@group.one"

[revsets]
'bookmark-advance-to' = 'latest(trunk()::@ ~ description(exact:"") ~ empty())'

[aliases]
# Show the "head" of what's being done:
#  - Current revset to trunk() ('@..trunk()', but .. excludes trunk())
#  - Where master/main is ('trunk()')
#  - 5 most recent commits on other branches ('ancestors(visible_heads(), 5)')
# And then pick the 15 most recent of all those ('latest(..., 15)')
# rebase-all = ['rebase', '--branch', 'mutable() & mine()', '--destination', 'trunk()']
link = ['util', 'exec', '--', 'jj-link']
up = ["util", "exec", "--", "bash", "-c", """
#!/usr/bin/env bash
set -euo pipefail
jj git fetch --all-remotes
jj rebase --branch 'mutable() & mine()' --destination 'trunk()'
"""]
jj = ["util", "exec", "--", "jj"]

[templates]
git_push_bookmark = '"msi/" ++ change_id.short()'
# draft_commit_description = '''
#   concat(
#     coalesce(description, default_commit_description, "\n"),
#     surround(
#       "\nJJ: This commit contains the following changes:\n", "",
#       indent("JJ:     ", diff.stat(72)),
#     ),
#     "\nJJ: ignore-rest\n",
#     diff.git(),
#   )
# '''

[git]
private-commits = '''description(glob:'WIP:*') | description(glob:'wip:*')'''
write-change-id-header = true

[fix.tools.buildifer]
command = ["buildifier", "-lint=fix", "-path=$path"]
patterns = ["glob:**/*.bazel", "glob:**/*.bzl"]

[fix.tools.justfile-format]
command = ["just", "--justfile", "/dev/stdin", "--dump"]
patterns = ["justfile", ".justfile"]

[fix.tools.go-format]
command = ["gofmt", "-s"]
patterns = ["glob:**/*.go"]

# Doesn't work (yet) as `buf format` doesn't accept data on stdin
# https://github.com/bufbuild/buf/issues/1035 
# [fix.tools.buf-format]
# command = ["buf", "format", "--verbose", "/dev/stdin", "-o", "/dev/stdout"]
# patterns = ["glob:**/*.proto"]


[ui]
default-command = "log"
diff-editor = ":builtin"

# Try difftastic (https://difftastic.wilfred.me.uk/jj.html)
#diff-formatter = ":git"
diff-formatter = ["difft", "--color=always", "$left", "$right"]

merge-editor = ":builtin"
#pager = "delta"

[ui.movement]
# https://docs.jj-vcs.dev/latest/config/#behavior-of-prev-and-next-commands
edit = true
